[tool.poetry]
name = "terec-io"
version = "0.1.0"
description = "TEst REsult Collector"
authors = ["Tomek Lasica <tlasica@life.pl>"]
license = "MIT"
readme = "README.md"
packages = [{include = "terec"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
