version: '3'

services:
  terec-cassandra:
    image: "cassandra:5.0.3"
    environment:
      JVM_OPTS: -Dcassandra.skip_wait_for_gossip_to_settle=0
      CASSANDRA_CLUSTER_NAME: terec
    healthcheck:
      test: ["CMD", "cqlsh", "127.0.0.1", "-e", "SHOW VERSION;"]
      interval: 10s
      timeout: 10s
      retries: 5
  terec-api:
    image: "terec/api:latest"
    ports:
      - "8000:8000"
    depends_on:
      terec-cassandra:
        condition: service_healthy
    environment:
      CASSANDRA_HOSTS: terec-cassandra
      CASSANDRA_KEYSPACE: terec
