name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
      checks: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: '1.6.1'
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: |
        poetry install

    - name: Run tests
      run: |
        poetry run pytest --keepalive --benchmark-skip --cov=terec --cov-report=xml --junitxml=pytest-report.xml
        ls -l pytest-report.xml

    - name: Store test results
      continue-on-error: true
      env:
        TEREC_URL: https://terec-api.fly.dev
        TEREC_API_KEY: ${{ secrets.TEREC_API_WRITE_TOKEN }}
        TEREC_ORG: terec
        TEREC_PROJECT: terec
        BRANCH_NAME: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      run: |
        echo "branch name ${BRANCH_NAME} run number {GITHUB_RUN_NUMBER}"
        ls -la
        poetry run cli junit import ./pytest-report.xml ${BRANCH_NAME} ${GITHUB_RUN_NUMBER}
